# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateTimeField()),
                ('to', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=256)),
                ('text', models.TextField(max_length=32768)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server_address', models.CharField(max_length=128)),
                ('tcp_port', models.IntegerField(default=995)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailmessages.Provider')),
            ],
        ),
    ]
