# Generated by Django 2.1.1 on 2018-09-08 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailmessages', '0002_auto_20171106_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMailAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailmessages.EMailAccount'),
        ),
    ]
